version: '3.3'
services:
  clean-architecture-laravel-app:
    container_name: clean-architecture-laravel-app
    build:
      context: ./
      dockerfile: ops/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ./vendor:/app/vendor:cached
      - ./node_modules:/app/node_modules:cached
    ports:
      - 8080:80
    tty: true
    environment:
      DATABASE_HOST: "takeaway-mysql"
      DATABASE_PORT: "3306"
    env_file:
      - .env
    depends_on:
      - takeaway-mysql
  clean-architecture-laravel-mysql:
    image: mysql:5.7
    container_name: clean-architecture-laravel-mysql
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "clean_architecture"
      TZ: "Europe/Amsterdam"
    ports:
      - 3306:3306
